import '@/app/styles.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" type="x-icon" href='../public/next.svg'></link>
      </head>
      <body>{children}</body>
    </html>
  )
}
